### ISSUE TITLE
Need to properly handle adding a new ismKey to the database

### ISSUE THREAD

**Issue by tj1023xbl** [tj1023xbl/Discord.Bot.IsmsBot#4]
https://github.com/tj1023xbl/Discord.Bot.IsmsBot/blob/025a1b757e3f569a794dfb14b7568d529c54e49b/src/Discord.Bot.IsmsBot/Services/Isms/IsmsService.cs#L45

Currently seems like this would just throw an exception when we can't find an imsKey, rather than continuing on to create a new entry.

**Comment by tybird13** [comment]
Made the required changes.
